name: Angular-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut
        uses: actions/checkout@v4

      - name: List files for debugging
        run: ls -la

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20.12.2"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:prod

      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: funcionalidad/caoo-examen
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
